spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customerDb
    username: Ecommerce
    password: Ecommerceee@123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8090