spring:
  data:
    mongodb:
      username: Ecommerce
      password: Ecommerceee@123
      host: localhost
      port: 27017
      database: notificationDb
      authentication-database: admin

  kafka:
    consumer:
      bootstrap-server: localhost:9092
      group-id: paymentGroup, orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      #for the security purpose we inform the consumer about the package that we are sending
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: orderConfirmation:com.microservices.Notification.service.resource.OrderConfirmation, paymentConfirmation:com.microservices.Notification.service.resource.PaymentConfirmation
  mail:
    host: localhost
    port: 1025
    username:
    password:
    protocol: smtp
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
server:
  port: 8096